(() => {
  // Optional AI vision endpoint. Keep this namespaced module self-contained when integrating.
  // Configure window.FIELDNOTE_AI_ENDPOINT before this script. Use an authenticated backend proxy,
  // never expose provider API keys in browser code. Expected JSON: {plate, vehicle, estimatedTime,
  // services:[{type,title,estimatedTime}]}. `services` can return individual estimates.
  const AI_ANALYSIS_ENDPOINT = window.FIELDNOTE_AI_ENDPOINT || '';
  const DB_NAME = 'fieldnote_vehicle_records';
  const STORE = 'vehicles';
  const $ = (selector, root = document) => root.querySelector(selector);
  const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
  const nowISO = () => new Date().toISOString();
  const makeId = () => crypto.randomUUID ? crypto.randomUUID() : `fn-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const esc = (value = '') => String(value).replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const estimates = {Repair:'About 2 hours',Wash:'About 40 minutes',Rental:'About 30 minutes',Sales:'About 1 hour'};
  const defaultTitles = {Repair:'Repair and inspection',Wash:'Vehicle wash',Rental:'Rental handover',Sales:'Vehicle sales enquiry'};
  const types = ['Repair','Wash','Rental','Sales'];
  let db, records = [], activeFilter = 'all', selectedId = null, pendingConfirmId = null;
  let toastTimer, cameraStream = null, currentPhoto = '', estimateTimer = null, visionLibraryPromise = null, facingMode = 'environment';

  function openDb() {
    return new Promise((resolve, reject) => {
      const request = indexedDB.open(DB_NAME, 1);
      request.onupgradeneeded = () => request.result.createObjectStore(STORE, {keyPath:'id'});
      request.onsuccess = () => resolve(request.result);
      request.onerror = () => reject(request.error);
    });
  }
  function dbRequest(mode, action) {
    return new Promise((resolve, reject) => {
      const tx=db.transaction(STORE,mode), request=action(tx.objectStore(STORE));
      request.onsuccess=()=>resolve(request.result); request.onerror=()=>reject(request.error);
    });
  }
  const allRecords=()=>dbRequest('readonly',store=>store.getAll());
  const saveRecord=record=>dbRequest('readwrite',store=>store.put(record));
  const ago=minutes=>new Date(Date.now()-minutes*60000).toISOString();
  const seedRecords=()=>[
    {id:'sample-1',plate:'KPH482',vehicle:'Toyota RAV4 · 2021',customer:'Mia Chen',phone:'021 445 830',service:'Repair',status:'in_progress',estimate:'About 1 hr 20 min',request:'A noise when starting. Please inspect the brakes and belt first. Call before any work over the $600 budget.',photo:'',createdAt:ago(143),events:[{at:ago(18),title:'Brake and belt inspection in progress',note:'Technician noted light belt wear; inspection continues.'},{at:ago(143),title:'Service record created',note:'Vehicle checked in and customer request recorded.'}]},
    {id:'sample-2',plate:'LQW731',vehicle:'Honda Fit · 2019',customer:'James Wilson',phone:'022 809 144',service:'Wash',status:'pending',estimate:'About 35 min',request:'Interior and exterior clean. Please pay extra attention to pet hair in the boot.',photo:'',createdAt:ago(68),events:[{at:ago(68),title:'Service record created',note:'Vehicle checked in and is waiting to be assigned.'}]},
    {id:'sample-3',plate:'NZT205',vehicle:'Mazda CX-5 · 2022',customer:'Sarah Lee',phone:'027 551 097',service:'Repair',status:'done',estimate:'Completed',request:'Routine service, oil and filter change.',photo:'',createdAt:ago(290),events:[{at:ago(72),title:'Service completed',note:'Oil and filter changed; road test complete.'},{at:ago(260),title:'Work started',note:'Technician began the routine service.'},{at:ago(290),title:'Service record created',note:'Customer approved the listed service.'}]},
    {id:'sample-4',plate:'JRM619',vehicle:'Subaru Outback · 2020',customer:'Oliver Park',phone:'021 901 662',service:'Rental',status:'in_progress',estimate:'Ready for pickup at 4:30 PM',request:'Vehicle is prepared for pickup. Confirm fuel level and note the existing scratch on the right rear door at handover.',photo:'',createdAt:ago(350),events:[{at:ago(33),title:'Vehicle preparation complete',note:'Fuel 7/8; existing right rear door scratch recorded.'},{at:ago(350),title:'Service record created',note:'Rental record created.'}]}
  ];
  const dateLabel=value=>new Intl.DateTimeFormat('en-NZ',{month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value));
  const itemStatusLabel=status=>status==='completed'?'Completed':status==='in_progress'?'In progress':'Not started';
  const itemStatusClass=status=>status==='completed'?'completed':status==='in_progress'?'':'not-started';
  const typeClass=type=>({Repair:'repair',Wash:'wash',Rental:'rental',Sales:'sales'})[type]||'';
  function getItems(record){return record.services?.length?record.services:[];}
  function overallStatus(record){const services=getItems(record);if(!services.length)return 'not_started';if(services.every(service=>service.status==='completed'))return 'completed';if(services.every(service=>service.status==='not_started'))return 'not_started';return 'in_progress';}
  function normalizeRecord(record){if(Array.isArray(record.services)&&record.services.length)return record;const type=types.includes(record.service)?record.service:'Repair';const status=record.status==='done'?'completed':record.status==='pending'?'not_started':record.status==='in_progress'?'in_progress':'not_started';const normalized={...record,services:[{id:makeId(),type,title:defaultTitles[type],status,estimate:record.estimate||estimates[type],request:record.request||'',events:record.events||[]}]};delete normalized.service;delete normalized.estimate;delete normalized.request;delete normalized.events;return normalized;}
  function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2800);}
  function filteredRecords(){const query=$('#searchInput').value.trim().toLowerCase();return [...records].filter(record=>{const status=overallStatus(record);const filterMatch=activeFilter==='all'||status===activeFilter;const serviceNames=getItems(record).map(item=>`${item.type} ${item.title}`).join(' ');const queryMatch=!query||[record.plate,record.vehicle,record.customer,serviceNames].some(value=>(value||'').toLowerCase().includes(query));return filterMatch&&queryMatch;}).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));}
  function render(){const items=filteredRecords();$('#vehicleRows').innerHTML=items.map(record=>{const status=overallStatus(record),allEvents=getItems(record).flatMap(service=>service.events||[]).sort((a,b)=>new Date(b.at)-new Date(a.at));const latest=allEvents[0];const services=getItems(record);return `<tr data-id="${esc(record.id)}"><td><div class="vehicle-cell"><div class="car-thumb">${record.photo?`<img src="${record.photo}" alt="Vehicle">`:'⌁'}</div><div><div class="plate">${esc(record.plate)}</div><div class="car-meta">${esc(record.vehicle||'Vehicle details pending')}</div><div class="customer-name">${esc(record.customer||'Customer not listed')}</div></div></div></td><td><div class="service-list">${services.map(service=>`<span class="service-tag ${typeClass(service.type)}" title="${esc(service.title)}">${esc(service.type)}</span>`).join('')}</div></td><td><span class="status ${itemStatusClass(status)}"><i></i><span class="status-label">${itemStatusLabel(status)}</span></span><span class="substatus">${services.length} service item${services.length===1?'':'s'}</span></td><td><span class="estimate ${status==='completed'?'muted':''}">${esc(status==='completed'?'—':services.length===1?services[0].estimate||'To be assessed':`${services.filter(s=>s.status!=='completed').length} active estimates`)}</span></td><td><span class="recent">${latest?dateLabel(latest.at):'—'}</span></td><td><button class="row-action" aria-label="Open service record">···</button></td></tr>`;}).join('');
    $('#emptyState').classList.toggle('hidden',items.length>0);$('#vehicleRows').closest('.table-wrap').querySelector('table').classList.toggle('hidden',items.length===0);$('#countAll').textContent=records.length;$('#filterAll').textContent=records.length;$('#countNotStarted').textContent=records.filter(record=>overallStatus(record)==='not_started').length;$('#countActive').textContent=records.filter(record=>overallStatus(record)==='in_progress').length;$('#countDone').textContent=records.filter(record=>overallStatus(record)==='completed').length;$('#listSummary').textContent=`Showing ${items.length} of ${records.length} vehicle records`;}
  function selected(){return records.find(record=>record.id===selectedId);}
  function renderServiceCard(service){const events=[...(service.events||[])].sort((a,b)=>new Date(b.at)-new Date(a.at));const next=service.status==='not_started'?'Start work':service.status==='in_progress'?'Complete work':'';return `<article class="service-card" data-service-id="${esc(service.id)}"><div class="service-card-head"><div><h4 class="service-item-title">${esc(service.title)}</h4><div class="service-item-meta"><span class="service-tag ${typeClass(service.type)}">${esc(service.type)}</span> · ${esc(service.estimate||'Estimate pending')}</div></div><span class="status ${itemStatusClass(service.status)}"><i></i><span class="status-label">${itemStatusLabel(service.status)}</span></span></div><div class="service-item-details"><div><div class="detail-key">Estimated time</div><div class="detail-val">${esc(service.estimate||'To be assessed')}</div></div><div><div class="detail-key">Latest update</div><div class="detail-val">${events[0]?dateLabel(events[0].at):'No updates yet'}</div></div></div>${service.request?`<div class="service-item-request">${esc(service.request)}</div>`:''}<div class="service-item-actions">${next?`<button class="primary-button service-progress" data-service-id="${esc(service.id)}">${next} <span>→</span></button>`:''}<button class="quiet-change change-status" data-service-id="${esc(service.id)}">Change status</button><button class="link-button service-note" data-service-id="${esc(service.id)}">＋ Add update</button></div><div class="change-confirm hidden" id="confirm-${esc(service.id)}"><span>Confirm ${service.status==='not_started'?'starting':'completion'} of “${esc(service.title)}”?</span><span><button class="link-button cancel-progress" data-service-id="${esc(service.id)}">Cancel</button><button class="primary-button confirm-progress" data-service-id="${esc(service.id)}">Confirm</button></span></div><div class="service-history">${events.slice(0,3).map(event=>`<div class="mini-event"><span>${dateLabel(event.at)}</span><b>${esc(event.title)}</b>${event.note?`<small>${esc(event.note)}</small>`:''}</div>`).join('')}${events.length>3?`<button class="link-button show-history" data-service-id="${esc(service.id)}">View all ${events.length} updates</button>`:''}</div></article>`;}
  function renderDetail(){const record=selected();if(!record)return;$('#detailContent').innerHTML=`<div class="detail-hero"><div class="detail-photo">${record.photo?`<img src="${record.photo}" alt="${esc(record.plate)}">`:'⌁'}</div><div><div class="detail-plate">${esc(record.plate)}</div><div class="detail-car">${esc(record.vehicle||'Vehicle details pending')}</div><div class="detail-client">${esc(record.customer||'Customer not listed')}${record.phone?` · ${esc(record.phone)}`:''}</div><div style="margin-top:9px"><span class="status ${itemStatusClass(overallStatus(record))}"><i></i><span class="status-label">${itemStatusLabel(overallStatus(record))}</span></span></div></div></div><div class="detail-sections"><div style="display:flex;align-items:center;justify-content:space-between"><h3 class="section-title" style="margin:0">Service details <span class="total-count">${getItems(record).length}</span></h3><span class="detail-key">Each service has its own status and history</span></div><div class="service-card-list" style="margin-top:13px">${getItems(record).map(renderServiceCard).join('')}</div></div><div class="detail-sections"><h3 class="section-title">Vehicle and customer request</h3><div class="request-box">${esc(record.request||'No general handover notes added.')}</div><div class="detail-grid" style="margin-top:12px"><div><div class="detail-key">Checked in</div><div class="detail-val">${dateLabel(record.createdAt)}</div></div><div><div class="detail-key">Vehicle registration</div><div class="detail-val">${esc(record.plate)}</div></div></div></div>`;
    $$('.service-progress', $('#detailContent')).forEach(button=>button.addEventListener('click',()=>{const confirm=$(`#confirm-${CSS.escape(button.dataset.serviceId)}`);confirm.classList.remove('hidden');}));
    $$('.confirm-progress', $('#detailContent')).forEach(button=>button.addEventListener('click',()=>changeServiceProgress(button.dataset.serviceId)));
    $$('.cancel-progress', $('#detailContent')).forEach(button=>button.addEventListener('click',()=>{$(`#confirm-${CSS.escape(button.dataset.serviceId)}`).classList.add('hidden');}));
    $$('.change-status', $('#detailContent')).forEach(button=>button.addEventListener('click',()=>openStatusModal(button.dataset.serviceId)));
    $$('.service-note', $('#detailContent')).forEach(button=>button.addEventListener('click',()=>addServiceNote(button.dataset.serviceId)));
    $$('.show-history', $('#detailContent')).forEach(button=>button.addEventListener('click',()=>showFullHistory(button.dataset.serviceId)));
  }
  function findService(serviceId){return getItems(selected()).find(service=>service.id===serviceId);}
  async function changeServiceProgress(serviceId){const record=selected(),service=findService(serviceId);if(!record||!service)return;const at=nowISO();if(service.status==='not_started'){service.status='in_progress';service.events.unshift({at,title:'Work started',note:'Service work has started.'});}else if(service.status==='in_progress'){service.status='completed';service.events.unshift({at,title:'Service completed',note:'Service item marked complete.'});}record.updatedAt=at;await saveRecord(record);await reload();renderDetail();toast(`${service.title}: ${itemStatusLabel(service.status)}`);}
  function openStatusModal(serviceId){const service=findService(serviceId);if(!service)return;$('#statusServiceItemId').value=service.id;$('#statusServiceTitle').value=`${service.type} — ${service.title}`;$('#statusSelect').value=service.status;$('#statusNote').value='';$('#statusOverlay').classList.remove('hidden');}
  async function saveStatusChange(event){event.preventDefault();const record=selected(),service=findService($('#statusServiceItemId').value);if(!record||!service)return;const next=$('#statusSelect').value,note=$('#statusNote').value.trim();if(!note)return toast('Add a short note explaining this update');const previous=service.status,at=nowISO();service.status=next;service.events.unshift({at,title:previous===next?'Service update':`Status changed: ${itemStatusLabel(previous)} → ${itemStatusLabel(next)}`,note});record.updatedAt=at;await saveRecord(record);await reload();closeOverlay('statusOverlay');renderDetail();toast('Status and service history updated');}
  async function addServiceNote(serviceId){const service=findService(serviceId);if(!service)return;const note=window.prompt(`Add an update for “${service.title}”`);if(note===null)return;if(!note.trim())return toast('Add a short note to save this update');service.events.unshift({at:nowISO(),title:'Progress update',note:note.trim()});selected().updatedAt=nowISO();await saveRecord(selected());await reload();renderDetail();toast('Service update saved');}
  function showFullHistory(serviceId){const service=findService(serviceId);if(!service)return;const history=[...(service.events||[])].sort((a,b)=>new Date(b.at)-new Date(a.at)).map(event=>`${dateLabel(event.at)} — ${event.title}${event.note?`\n${event.note}`:''}`).join('\n\n');window.alert(`${service.type} — ${service.title}\n\n${history}`);}
  function closeOverlay(id){$(`#${id}`).classList.add('hidden');if(id==='cameraOverlay')stopCamera();}
  function openDetail(id){selectedId=id;renderDetail();}
  function chooseServices(){return $$('.service-checks input:checked').map(input=>input.value);}
  function renderServiceInputs(preserve=true){const prior={};$$('.service-item-input', $('#serviceItemInputs')).forEach(row=>{const type=row.dataset.type;prior[type]={title:$('.service-title-input',row).value,estimate:$('.service-estimate-input',row).value};});const selected=chooseServices();$('#serviceItemsField').classList.toggle('hidden',selected.length===0);$('#serviceItemInputs').innerHTML=selected.map(type=>{const values=preserve&&prior[type]?prior[type]:{title:defaultTitles[type],estimate:estimates[type]};return `<div class="service-item-input" data-type="${type}"><span class="service-tag ${typeClass(type)}">${type}</span><input class="service-title-input" type="text" aria-label="${type} service item title" value="${esc(values.title)}" placeholder="Service item title" required><input class="service-estimate-input" type="text" aria-label="${type} estimated time" value="${esc(values.estimate)}" placeholder="Est. time"><span class="service-estimate-mark">editable</span></div>`;}).join('');}
  function openIntake(){const form=$('#intakeForm');form.reset();currentPhoto='';$$('.service-checks input').forEach(input=>input.checked=false);renderServiceInputs(false);$('#photoPreview').innerHTML='<span class="camera-glyph">▧</span><span>Take a photo or upload an image</span>';$('#scanHint').textContent='A clear registration plate helps OCR.';$('#estimateNote').textContent=AI_ANALYSIS_ENDPOINT?'Connected AI can suggest an estimate for each selected item. Review and edit before saving.':'Editable time suggestions are generated from service type. Connect an AI endpoint for vehicle-specific predictions.';$('#intakeOverlay').classList.remove('hidden');}
  function photoData(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});}
  async function loadOcr(){if(window.Tesseract)return window.Tesseract;if(!visionLibraryPromise)visionLibraryPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';script.onload=()=>resolve(window.Tesseract);script.onerror=()=>reject(new Error('Could not load the photo text reader.'));document.head.appendChild(script);});return visionLibraryPromise;}
  async function scanPlateFromPhoto(){if(!currentPhoto)return toast('Take or upload a vehicle photo first');$('#scanPlateBtn').textContent='Reading…';$('#scanHint').textContent='Reading text in photo…';try{const tesseract=await loadOcr();const result=await tesseract.recognize(currentPhoto,'eng');const text=result.data.text.toUpperCase();const candidates=text.match(/\b[A-Z0-9]{5,8}\b/g)||[];const plate=candidates.find(value=>/[A-Z]/.test(value)&&/\d/.test(value));if(plate){$('#plateInput').value=plate;$('#scanHint').textContent=`Plate found: ${plate} · please verify`;toast(`Plate detected: ${plate}`);}else{$('#scanHint').textContent='No clear plate found. Enter it manually or retake the photo.';toast('Could not read a plate. Try a closer photo.');}}catch(error){console.error(error);$('#scanHint').textContent='Photo text reader could not load. Enter the plate manually.';toast(error.message||'Photo reading failed');}finally{$('#scanPlateBtn').textContent='Scan photo';}}
  async function runAiAnalysis(){if(!AI_ANALYSIS_ENDPOINT||!currentPhoto)return;const form=new FormData();form.append('photo',await (await fetch(currentPhoto)).blob(),'vehicle.jpg');form.append('serviceItems',JSON.stringify(chooseServices().map(type=>({type,title:$(`.service-item-input[data-type="${type}"] .service-title-input`)?.value||defaultTitles[type]}))));form.append('request',$('#requestInput').value.trim());form.append('service',chooseServices().join(','));$('#estimateNote').textContent='AI is analysing the vehicle photo and selected service items…';try{const response=await fetch(AI_ANALYSIS_ENDPOINT,{method:'POST',body:form});if(!response.ok)throw new Error(`AI service returned ${response.status}`);const result=await response.json();if(result.plate&&!$('#plateInput').value.trim())$('#plateInput').value=result.plate;if(result.vehicle&&!$('#vehicleInput').value.trim())$('#vehicleInput').value=result.vehicle;if(Array.isArray(result.services)){for(const item of result.services){const row=$(`.service-item-input[data-type="${CSS.escape(item.type)}"]`);if(row&&item.title)$('.service-title-input',row).value=item.title;if(row&&item.estimatedTime)$('.service-estimate-input',row).value=item.estimatedTime;}}else if(result.estimatedTime){const first=$('.service-estimate-input');if(first)first.value=result.estimatedTime;}$('#estimateNote').textContent='AI suggestions are ready. Review and edit service titles and estimates before saving.';}catch(error){console.error(error);$('#estimateNote').textContent='AI analysis was unavailable. Editable service-time suggestions are still available.';}}
  async function acceptPhoto(file){if(!file)return;if(!file.type.startsWith('image/'))return toast('Choose an image file');if(file.size>8*1024*1024)return toast('Photo must be 8 MB or smaller');try{currentPhoto=await photoData(file);$('#photoPreview').innerHTML=`<img src="${currentPhoto}" alt="Vehicle photo preview">`;$('#scanHint').textContent='Photo ready. Scan the registration or let connected AI analyse it.';runAiAnalysis();}catch(error){toast('Could not read this photo');}}
  async function startCamera(){if(!navigator.mediaDevices?.getUserMedia)return toast('Camera access requires HTTPS or localhost in a supported browser.');try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facingMode}},audio:false});$('#cameraVideo').srcObject=cameraStream;$('#cameraOverlay').classList.remove('hidden');}catch(error){console.error(error);toast('Camera access was blocked. Check browser permissions.');}}
  function stopCamera(){if(cameraStream){cameraStream.getTracks().forEach(track=>track.stop());cameraStream=null;}$('#cameraVideo').srcObject=null;}
  async function switchCamera(){facingMode=facingMode==='environment'?'user':'environment';stopCamera();await startCamera();}
  async function capturePhoto(){const video=$('#cameraVideo');if(!video.videoWidth)return toast('Camera is not ready yet');const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);canvas.toBlob(async blob=>{if(!blob)return toast('Could not capture photo');await acceptPhoto(new File([blob],'vehicle-photo.jpg',{type:'image/jpeg'}));stopCamera();closeOverlay('cameraOverlay');},'image/jpeg',.86);}
  function startRequestVoice(){startVoice('requestInput','#recordRequestBtn','en-NZ');}
  function startVoice(fieldSelector,buttonSelector,language){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return toast('Speech recognition is not available in this browser.');const recognition=new Recognition();recognition.lang=language;recognition.interimResults=false;recognition.maxAlternatives=1;const button=$(buttonSelector);button?.classList.add('recording');if(button)button.innerHTML='● <span>Listening…</span>';toast('Listening… speak clearly');recognition.onresult=event=>{const field=$(fieldSelector);const text=event.results[0][0].transcript;field.value=`${field.value.trim()}${field.value.trim()?' ':''}${text}`;field.dispatchEvent(new Event('input',{bubbles:true}));toast('Voice note added');};recognition.onerror=()=>toast('Speech was not recognised. Check microphone access.');recognition.onend=()=>{if(button){button.classList.remove('recording');button.innerHTML='◉ <span>Record</span>';}};recognition.start();}
  async function startDetailVoiceNote(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition)return toast('Speech recognition is not available in this browser.');const recognition=new Recognition();recognition.lang='en-NZ';recognition.interimResults=false;recognition.maxAlternatives=1;toast('Listening… speak clearly');recognition.onresult=async event=>{const service=findService($('#statusServiceItemId').value);if(!service)return;$('#statusNote').value=`${$('#statusNote').value.trim()}${$('#statusNote').value.trim()?' ':''}${event.results[0][0].transcript}`;};recognition.onerror=()=>toast('Speech was not recognised. Check microphone access.');recognition.start();}
  async function createRecord(event){event.preventDefault();const form=event.currentTarget,data=new FormData(form),selectedTypes=chooseServices(),plate=String(data.get('plate')||'').trim().toUpperCase();if(!plate)return toast('Enter or scan the registration number');if(!selectedTypes.length)return toast('Select at least one service');if(records.some(record=>record.plate.toUpperCase()===plate&&overallStatus(record)!=='completed'))return toast('This vehicle already has an active service record');const at=nowISO(),request=String(data.get('request')||'').trim();const services=selectedTypes.map(type=>{const row=$(`.service-item-input[data-type="${CSS.escape(type)}"]`);const title=$('.service-title-input',row)?.value.trim();if(!title)throw new Error(`Add a title for the ${type.toLowerCase()} service item`);return{id:makeId(),type,title,status:'not_started',estimate:$('.service-estimate-input',row)?.value.trim()||estimates[type],request,events:[{at,title:'Service item created',note:request||'Service item is waiting to start.'}]};});const record={id:makeId(),plate,vehicle:String(data.get('vehicle')||'').trim(),customer:String(data.get('customer')||'').trim(),phone:String(data.get('phone')||'').trim(),status:'not_started',request,photo:currentPhoto,services,createdAt:at,updatedAt:at};await saveRecord(record);await reload();closeOverlay('intakeOverlay');openDetail(record.id);toast(`${services.length} service item${services.length===1?'':'s'} created`);}
  async function reload(){records=(await allRecords()).map(normalizeRecord);for(const record of records)await saveRecord(record);render();}
  function exportData(){const blob=new Blob([JSON.stringify({exportedAt:nowISO(),vehicles:records},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`fieldnote-service-records-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);toast('Backup downloaded');}
  function initEvents(){
    $('#addCarBtn').addEventListener('click',openIntake);$('#emptyAddBtn').addEventListener('click',openIntake);$('#intakeForm').addEventListener('submit',event=>{try{createRecord(event).catch(error=>toast(error.message||'Could not save service record'));}catch(error){toast(error.message);}});$('#statusForm').addEventListener('submit',saveStatusChange);$('#searchInput').addEventListener('input',render);
    $('#filters').addEventListener('click',event=>{const button=event.target.closest('[data-filter]');if(!button)return;activeFilter=button.dataset.filter;$$('.filter').forEach(el=>el.classList.toggle('active',el===button));render();});
    $('#vehicleRows').addEventListener('click',event=>{const row=event.target.closest('tr[data-id]');if(row)openDetail(row.dataset.id);});$('#exportBtn').addEventListener('click',exportData);$('#backupBtn').addEventListener('click',exportData);
    $$('[data-close]').forEach(button=>button.addEventListener('click',()=>closeOverlay(button.dataset.close)));$$('.overlay').forEach(overlay=>overlay.addEventListener('click',event=>{if(event.target===overlay)closeOverlay(overlay.id);}));
    $('#cameraBtn').addEventListener('click',startCamera);$('#uploadBtn').addEventListener('click',()=>$('#photoFile').click());$('#photoFile').addEventListener('change',event=>acceptPhoto(event.target.files[0]));$('#scanPlateBtn').addEventListener('click',scanPlateFromPhoto);$('#captureBtn').addEventListener('click',capturePhoto);$('#switchCameraBtn').addEventListener('click',switchCamera);
    $('#recordRequestBtn').addEventListener('click',startRequestVoice);$('#recordStatusBtn').addEventListener('click',()=>startVoice('statusNote','#recordStatusBtn','en-NZ'));
    $('#serviceChoices').addEventListener('change',()=>{renderServiceInputs();if(currentPhoto)runAiAnalysis();});$('#requestInput').addEventListener('input',()=>{if(currentPhoto&&AI_ANALYSIS_ENDPOINT){clearTimeout(estimateTimer);estimateTimer=setTimeout(runAiAnalysis,1200);}});
    document.addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();$('#searchInput').focus();}if(event.key==='Escape')$$('.overlay').forEach(overlay=>closeOverlay(overlay.id));});
  }
  async function init(){initEvents();try{db=await openDb();let existing=await allRecords();if(!existing.length){for(const item of seedRecords())await saveRecord(item);}await reload();}catch(error){console.error(error);toast('Local database unavailable. Open this page in a current browser over HTTPS or localhost.');}}
  init();
})();
